<?php

namespace App\Actions\Cash;

use App\Enums\AuditAction;
use App\Enums\CashTransactionType;
use App\Models\CashTransaction;
use App\Models\User;
use App\Services\Audit\AuditRecorder;
use App\Support\Money;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;

/**
 * Record or update a manual cash book entry.
 *
 * The stored amount is always positive; the direction of the money is carried by
 * the transaction type. Entries generated by the invoice or payroll modules are
 * never editable from here.
 */
class RecordCashTransactionAction
{
    public function __construct(private AuditRecorder $auditor) {}

    /** @param array<string, mixed> $data */
    public function handle(array $data, User $actor, ?CashTransaction $transaction = null): CashTransaction
    {
        return DB::transaction(function () use ($data, $actor, $transaction): CashTransaction {
            $amountMinor = abs(Money::toMinor($data['amount'] ?? 0));

            if ($amountMinor <= 0) {
                throw ValidationException::withMessages([
                    'amount' => 'Số tiền phải lớn hơn 0.',
                ]);
            }

            $attributes = [
                'branch_id' => $data['branch_id'],
                'type' => $data['type'],
                'category' => $data['category'],
                'amount' => Money::toDecimal($amountMinor),
                'payment_method' => ($data['payment_method'] ?? null) ?: null,
                'reference' => $data['reference'] ?? null,
                'note' => $data['note'] ?? null,
                'occurred_at' => $data['occurred_at'] ?? now(),
            ];

            if ($transaction === null) {
                $created = CashTransaction::query()->create($attributes + ['created_by' => $actor->id]);

                // Written inside the same transaction as the change, so the
                // trail can never be one commit behind the money.
                $this->auditor->record($created, $actor, AuditAction::Created, null, $created->auditSnapshot());

                return $created;
            }

            $this->guardManual($transaction);

            $before = $transaction->auditSnapshot();
            $transaction->forceFill($attributes)->save();

            $this->auditor->record($transaction, $actor, AuditAction::Updated, $before, $transaction->auditSnapshot());

            return $transaction;
        });
    }

    /** @throws ValidationException */
    public function guardManual(CashTransaction $transaction): void
    {
        if ($transaction->isSystemGenerated()) {
            throw ValidationException::withMessages([
                'type' => 'Giao dịch sinh tự động từ hóa đơn hoặc bảng lương không thể sửa trực tiếp.',
            ]);
        }

        if ($transaction->isVoided()) {
            throw ValidationException::withMessages([
                'type' => 'Giao dịch đã hủy không thể chỉnh sửa.',
            ]);
        }
    }

    /** Convenience helper for callers that only know the raw type string. */
    public static function typeFrom(string $value): CashTransactionType
    {
        return CashTransactionType::from($value);
    }
}
